# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.6.1
_src_path: gh:algorandfoundation/algokit-python-template
author_email: chaitanyakartikm@gmail.com
author_name: Chaitanya Kartik
contract_name: hello_world
deployment_language: python
preset_name: production
project_name: algo-project-contracts

